import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sample of a hosted website you can use to handle your universal links.
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://docs.expo.dev/guides/linking/#universaldeep-links-without-a-custom-scheme" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Expo Universal Links Documentation.</p>
          </a>

          <a
            href="https://expo-universal-links-website-template.vercel.app/.well-known/apple-app-site-association"
            className={styles.card}
          >
            <h2>Your Live AASA Link</h2>
            <p>
              Hopefully it returns JSON....
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
